/// <reference path="typings/angular-ui-bootstrap/angular-ui-bootstrap.d.ts"/>
/// <reference path="typings/angularjs/angular-cookies.d.ts"/>
/// <reference path="typings/angularjs/angular-resource.d.ts"/>
/// <reference path="typings/angularjs/angular-route.d.ts"/>
/// <reference path="typings/angularjs/angular-cookies.d.ts"/>
/// <reference path="typings/angularjs/angular-sanitize.d.ts"/>
/// <reference path="typings/angularjs/angular.d.ts"/>
/// <reference path="typings/jquery/jquery.d.ts"/>
//# sourceMappingURL=_references.js.map
